Refactor tests to cover multiple cpu models and multiple operating systems
Signed-off-by: Klaus Kämpf <kkaempf@gmail.com>

diff --git a/tests/runtest b/tests/runtest
--- a/tests/runtest
+++ b/tests/runtest
@@ -1,18 +1,27 @@
 #!/bin/sh
 #
-# test.sh <hex>
+# test.sh <CPU> <OS> <hex>
+#  CPU: 21064, 21164, 21264
+#  OS: NT, UNIX, VMS
 TMPDIR="."
-for i in $@; do \
-  echo -n "$i "; \
-  j=$(basename $i .hex); \
-  hex=$(grep -v ^\# $i | tr -d " \n"); \
-  asm=$j.out; \
-  $(sleigh-lift disassemble $SLA $hex > $asm); \
-  diff -wu $j.asm $asm; \
-  if [ $? -ne 0 ]; then \
-    echo "fail"; \
-    break; \
-  else \
-    echo "pass"; \
+CPU=$1
+OS=$2
+shift 2
+for i in $@; do
+  j=$(basename $i .hex);
+  echo -n "$i ";
+  hex=$(grep -v ^\# $i | tr -d " \n");
+  out=$j.out;
+  $(sleigh-lift disassemble $CPU$OS.sla $hex > $out);
+  if [ -f $j.asm$OS ]; then
+    diff -wu $j.asm$OS $out;
+  else
+    diff -wu $j.asm $out;
+  fi;
+  if [ $? -ne 0 ]; then
+    echo "fail";
+    break;
+  else
+    echo "pass";
   fi;
 done
